server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:mem:retail_order;db_close_on_exit=false
    driver-class-name: org.h2.Driver
    username: avenuecode
    password: avenuecode
    platform: h2
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  profiles: orders-test
 
logging:
  level:
    ROOT: info

